### ISSUE TITLE
Fails to build with Kea 2.0.0 (and Boost 1.77)

### ISSUE THREAD

**Issue by jirutka** [cvut/kea-hook-userchk-ldap#5]
```
In file included from user_registry.cc:10:
./user_registry.h:174:10: error: 'time_t' in namespace 'std' does not name a type; did you mean 'time_put'?
  174 |     std::time_t getInvalidAfter() const;
      |          ^~~~~~
      |          time_put
./user_registry.h:191:10: error: 'time_t' in namespace 'std' does not name a type; did you mean 'time_put'?
  191 |     std::time_t invalid_after_;
      |          ^~~~~~
      |          time_put
user_registry.cc: In constructor 'user_chk::Result::Result(user_chk::UserPtr, user_chk::ResultType, time_t)':
user_registry.cc:163:108: error: class 'user_chk::Result' does not have any field named 'invalid_after_'
  163 | Result::Result(const UserPtr user, ResultType result, time_t invalid_after): user_(user), result_(result), invalid_after_(invalid_after) { }
      |                                                                                                            ^~~~~~~~~~~~~~
user_registry.cc: At global scope:
user_registry.cc:179:1: error: no declaration matches 'time_t user_chk::Result::getInvalidAfter() const'
  179 | Result::getInvalidAfter() const {
      | ^~~~~~
user_registry.cc:179:1: note: no functions named 'time_t user_chk::Result::getInvalidAfter() const'
In file included from user_registry.cc:10:
./user_registry.h:149:7: note: 'class user_chk::Result' defined here
  149 | class Result {
      |       ^~~~~~
user_registry.cc: In member function 'bool user_chk::Result::isExpired() const':
user_registry.cc:185:11: error: 'invalid_after_' was not declared in this scope
  185 |   return (invalid_after_ <= std::time(nullptr));
      |           ^~~~~~~~~~~~~~
```

**Comment by jirutka** [comment]
It’s just a missing include. We need to add `#include <ctime>` to `user_registry.h`.
