### ISSUE TITLE
Fails to build with Kea 2.2.0

### ISSUE THREAD

**Issue by jirutka** [cvut/kea-hook-userchk-ldap#6]
```
In file included from /usr/include/kea/dhcpsrv/subnet.h:15,
                 from subnet_select_co.cc:15:
/usr/include/kea/dhcpsrv/network.h:17:10: fatal error: dhcpsrv/cfg_globals.h: No such file or directory
   17 | #include <dhcpsrv/cfg_globals.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:551: libducl_la-subnet_select_co.lo] Error 1
```

Kea doesn’t provide `dhcpsrv/cfg_globals.h` anymore.

I’m removing it from Alpine Linux Edge now due to this. The latest stable release with this plugin is Alpine v3.16 and Kea 2.0.3.

@geostarling Hopefully, we won’t need this plugin soon, so it’s probably not necessary to address this. Then we will archive this repository.
